#+TITLE: Flavie's Mail 1
#+AUTHOR: Laurent Garnier

* Mail part [1/2]
  This video clip dedramatises the need to be alone in stifling
  society. So fast, so agressive, so intense, social life must be
  dangerous on our sensibility and personality. (Never be alone it’s a
  risk to forget who we are).
* Mail [2/2]
  Actually, it explains us that solitary moments are a good way to
  find yourself, emotionally, and hence, to be more attentive to
  others. “Love your neighbor as yourself” but first, love you as
  yourself... be alone (a bit).
* Correction part [1/2]
  This video *tones down* the need to be alone in *a* stifling
  society. So fast, so agressive, so intense, social life *could* be
  dangerous on our sensitivity and personality. (Never be alone *is* a
  risk to forget who we are).
* Correction part [2/2]
  Actually, it explains us that solitary moments are a good way to
  find yourself, emotionally, and hence, to be more attentive to
  others. “Love your neighbor as yourself”, but first, love
  *yourself*... be alone (a bit).


