#+TITLE: Hugo's mail 2
#+AUTHOR: Laurent Garnier

* Mail part [1/3]

  I chosed the video about Adam Smith because i like that man and he
  is in my programm. I have find that the Smith’s life is very
  uninteresting.

  In this video, i learnt lot of things about him : first of all, I
  understand the Smith’s motivation and the reason why, he worked in
  economics.

  Smith was born in Scotland in 1723 and he studied in the economics’s
  university. For many economist, he is a guide especially for 4
  ideas :

* Mail part [2/3]

  The first : he dicovered the specialization, that is, you are more
  profitably when you split asks in the entreprise. For him, economics
  will be richer.

  The second : he insisted on consumer capitalism : Smith thought that
  a consumer’s society, if we consume a lot, there are more
  wealth. That’s a reason why, through him, the luxury became
  accessible to middle classes.

* Mail part [3/3]

  The third : Smith succeed in render economics more rich through to
  rich’s people. He understands that rich’people prefer to be loved
  and to approve of, in this way, they fund : School, hospital, pay
  their workers well.

  The fourth : you don’t must to be swindle, and Smith explains that
  children must to be bring up in order to know good price to each
  object.

  I loved this video, through it, i can to learn lot of things about
  Smith. I find the video, in itself, is very good, i really liked
  watching this video

* Correction Mail part [1/3]

  I *chose* the video about Adam Smith because *I* like that man and he
  is in my programm. I have *found* that *Smith’s* life *was* very
  *interesting*.

  In this video, *I* learnt lot of things about him: first of all, I
  *understood* Smith’s motivation and the reason why, he worked in
  *the economics field*.

  Smith was born in Scotland in 1723 and he studied economics *at*
  university. For many *economists*, he is a guide especially for 4
  ideas: 

* Correction Mail part [2/3]

  *First:* he dicovered the specialization, that is, you are more
  *effective* when you split *tasks* in the *company*. For him, economics
  will be richer.

  *Second:* he insisted on consumer capitalism: Smith thought that
  *in* a consumer’s society, if we consume a lot, there *will be* more
  wealth. That’s a reason why, *thanks to* him, the luxury became (has become)
  accessible to middle classes...
* Correction Mail part [3/3]

  Third: Smith succeed in render economics *rich* through to
  rich’s people. He *understood* that rich people prefer to be loved
  and to *be approved* *by people*. *In order to lead people to* this
  way, they fund: schools, hospitals, pay their workers well...

  Fourth: you *mustn't* to be swindle, and Smith explains that
  children *must be brought up* in order to know *the* good price *for* each
  object.

  I loved this video, through it, *I* can to learn *lots* of things about
  Smith. I find the video, in itself, very good, *I* really liked
  watching this video
