#+TITLE: Les nombres
#+AUTHOR: Laurent Garnier

* Introduction
  Chaque fois que l'on a besoin de compter, mesurer, on a besoin de
  nombres. Que cela soit pour dénombrer (un moniteur de centre aéré
  qui souhaite vérifier qu'il n'a perdu aucun enfant), pour mesurer
  une masse (par exemple au marché pour les fruits et légumes), on
  n'utilisera pas toujours les mêmes nombres. 

  #+BEGIN_QUOTE
  Dieu a inventé les nombres entiers, le reste est l'oeuvre de
  l'homme.

  [[https://fr.wikipedia.org/wiki/Leopold_Kronecker][Leopold Kronecker]]
  #+END_QUOTE

* Les nombres entiers

  Sauf si vous avez eu un accident ou une mal formation, a priori vous
  avez dix doigts. De ce fait si vous commencez avec le pouce de votre
  main gauche avec 1, ensuite vous passez à l'index ce qui fera 2,
  puis au majeur ce qui fera 3, et ainsi de suite jusqu'à
  l'auriculaire de la main droite et ça fera 10. De façon /simplifiée/
  on dit que les entiers naturels sont ceux que l'on peut compter avec
  les doigts auxquels on ajoute zéro. En théorie, si l'on disposait
  d'un temps infini on pourrait compter n'importe quel nombre entier
  avec nos doigts. Mais au fait, pourquoi choisir uniquement nos 10
  doigts des mains ? Après tout on pourrait tout à fait continuer avec
  nos 10 orteils ce qui nous amènerait à 20. Et pourquoi ne pas
  compter nos phalanges pendant que nous y sommes ?

  Toutes ces questions qui peuvent vous paraître étranges ou au
  contraire légitimes sont là pour apprendre ou vous rappeler (si vous
  le saviez déjà) que même en mathématiques (en fait surtout) il
  s'agit avant tout de définir des conventions. Pour parler plus
  simplement on peut dire que l'on se met d'accord sur les règles du
  jeu. Pour le moment on ne va pas parler de ces autres systèmes
  potentiels (ou bases de numération). Mais soyez assurés que nous y
  reviendrons en temps voulu pour approfondir ces notions. 

  Pour résumer, on va commencer par les nombres que "tout le monde
  connaît", les entiers naturels 
  
  \[\mathbb{N} = \{0, 1, 2, 3, \dots \}\]

  Auxquels on ajoutera les entiers relatifs c'est-à-dire les
  nombres entiers positifs et négatifs. Ceux qui servent pour exprimer
  la température en Sibérie pendant l'hiver, ou pour indiquer le
  niveau du parking souterrain dans les ascenseurs. Les entiers
  relatifs sont notés 
  
  \[\mathbb{Z} = \{\dots, -3, -2, -1, 0, 1, 2, 3, \dots\}\]


* Les nombres rationnels ou fractions
  Que représente 15 minutes pour 1 heure ? Facile, cela représente 1/4
  d'heure. Que représente la partie d'un terrain de foot réservée à
  l'équipe des visiteurs ? La moitié du terrain soit 1/2
  terrain. Que représente une part de pizza lorsque celle-ci a été
  découpé (équitablement !) en 6 parts ? Facile, 1/6 de la pizza. 

  Dans toutes ces situations nous parlons de découpage (du temps, du
  terrain ou d'une pizza) en parties égales et entières. On appelle
  cela des fractions. Bien que de nos jours il soit plus répandu
  d'utiliser une écriture décimale, les fractions permettent de
  traiter plus de nombres. 

  Voici quelques équivalences classiques

  | Fraction | écriture décimale | Pourcentage |
  |----------+-------------------+-------------|
  | 1/2      | 0,5               |         50% |
  | 1/4      | 0,25              |         25% |
  | 3/4      | 0,75              |         75% |
  | 1/5      | 0,2               |         20% |
  | 2/5      | 0,4               |         40% |
  | 3/5      | 0,6               |         60% |
  | 4/5      | 0,8               |         80% |
  | 1/10     | 0,1               |         10% |
  | 3/10     | 0,3               |         30% |
  
  En revanche il faut se méfier de certaines fractions

  #+BEGIN_SRC LATEX
  \begin{align*}
  \dfrac{1}{3} &\neq 0,33 \\
  \dfrac{2}{3} &\neq 0,66 \\
  \dfrac{1}{6} &\neq 0,16 
  \end{align*}
  #+END_SRC

  Mais chaque fois que vous manipulez des euros et des centimes (en
  fait n'importe quelle [[https://www.wikiberal.org/wiki/Monnaie-fiat][monnaie-fiat]] ferait l'affaire) vous utilisez
  des fractions. Par exemples :
  + Un croissant à 80 centimes vaut 80/100 d'euros soit 8/10 ou encore
    4/5. 
  + Si un t-shirt à 15€ subi une remise de 10% pendant les soldes alors vous
    ne paierez que 90% du prix, ainsi $15\times \frac{90}{100} =
    \dfrac{935}{100} = 9,35€$
    

  On appel l'ensemble des fractions, l'ensemble des nombres rationnels
  (pensez à votre ration [part, portion] à la cantine), l'ensemble de
  tous les quotients d'entiers relatifs dont le dénominateur (le
  nombre en dessous) n'est pas zéro : 

  \[\mathbb{Q} = \{ \dfrac{a}{b} | a\in\mathbb{Z},
  b\in\mathbb{N}^{*}\}\]
  
  Avec $\mathbb{N}^{*} = \mathbb{N}\{0} = \{1, 2, 3, \dots\}$
  c'est-à-dire tous les entiers naturels sauf zéro.


* Les nombres réels
  La légende raconte que le disciple de Pythagore [[https://fr.wikipedia.org/wiki/Hippase_de_M%25C3%25A9taponte][Hippase de Métaponte]]
  aurait découvert que certains nombres ne peuvent pas s'écrire à
  l'aide de fraction. Et cette même légende raconte que les autres
  pythagoriciens n'auraient pas vraiment apprécié cette
  découverte... au point qu'ils le laissèrent tout seul au large.

  Je ne sais pas si c'est vrai mais en revanche je sais que si vous
  prenez un carré de côté 1 alors sa diagonale aura pour longueur
  $\sqrt{2}$ et qu'il est impossible d'écrire ce nombre à l'aide d'une
  fraction. Les plus impatients peuvent d'ores et déjà chercher une
  démonstration de ce résultat. Pour les autres il vous faudra
  patienter encore un peu, mais c'est promis je vous livrerai une
  démonstration complète de ce résultat. 

  Il existe d'autres nombres célèbres qui ne peuvent pas s'écrire sous
  la forme de fractions :
  + le [[https://fr.wikipedia.org/wiki/Nombre_d%2527or][nombre d'or]] souvent noté $\Phi$
  + le nombre [[https://fr.wikipedia.org/wiki/Pi][Pi]] noté $\pi$
  + le nombre [[https://fr.wikipedia.org/wiki/E_(nombre)][e]] appelé constante d'[[https://fr.wikipedia.org/wiki/Leonhard_Euler][Euler]]

  Et bien d'autres. L'ensemble des nombres réels est l'ensemble de
  tous les nombres que l'on obtiendrait en identifiant l'abscisse de
  chaque point d'une droite. Prenez une droite quelconque, placer une
  encoche à un endroit particulier et attribuez ainsi à cette encoche
  l'abscisse 0. En procédant de cette manière, tout point de cette
  droite est associé à un unique nombre, qu'on appelle nombre réel. 
  L'ensemble des nombres réels est noté :
  
  \[\mathbb{R} = \{\dots, -\sqrt{3}, \dots,-\dfrac{3}{3}, \dots,  -\sqrt{2}, \dots, -1,
  \dots, 0, \dots, 1, \dots, \Phi, \dots, e, \dots, \pi, \dots \}\]
* Récapitulatif

  En guise de résumé, nous avons vu :
  1. Les nombres "qu'on peut compter avec les doigts", $\mathbb{N} =
     \{0, 1, 2, 3, \dots \}$
  2. Les nombres "qui servent à indiquer le niveau des températures",
     $\mathbb{Z} = \{\dots, -3, -2, -1, 0, 1, 2, 3, \dots\}$
  3. Les nombres fractionnaires $\mathbb{Q} = \{ \dfrac{a}{b} |
     a\in\mathbb{Z}, b\in\mathbb{N}^{*}\}$
  4. Les nombres réels $\mathbb{R} = \{\dots, -\sqrt{3},
     \dots,-\dfrac{3}{3}, \dots,  -\sqrt{2}, \dots, -1, \dots, 0,
     \dots, 1, \dots, \Phi, \dots, e, \dots, \pi, \dots \}$

  
  Mais attention, l'histoire n'est pas finie, il existe bien d'autres
  nombres... Nous en verrons quelques uns un peu (beaucoup ?) plus tard.
