#+TITLE: Les opérations
#+AUHTOR: Laurent Garnier

* Introduction
  Si l'on y réfléchit, il n'y a vraiment que _deux_ opérations,
  l'addition et la multiplication (et si on pousse le raisonnement un
  peu plus loin il n'y en a plus qu'une). En effet, une soustraction
  du nombre $a$ n'est rien d'autre que l'addition du nombre opposéé $-a$,
  et une division par $b$ est une multiplication par le nombre inverse
  $1/b$. 
* L'addition 
  Dans l'addition 2 + 5,3 = 7,3; les *termes* sont 2 et 5,3 et la
  [[https://fr.wiktionary.org/wiki/somme][somme]] est 7,3. 

  Tout nombre admet un opposé et la somme de deux opposés vaut 0.

  
   \begin{align*}
   2 + (-2) &= 0\\
   3 + (-3) &= 0\\
   4 + (-4) &= 0\\
   a + (-a) &= 0
   \end{align*}
  

** Exercice 1
   Trouver les nombres opposés aux nombres suivants :
   1. L'opposé du nombre $5$ est : 
   2. L'opposé du nombre $(-6)$ est : 
   3. L'opposé du nombre $(-1,5)$ est :
   4. L'opposé du nombre $\pi$ est :
   5. L'opposé du nombre $-\dfrac{1}{3}$ est :
** Ses propriétés  
*** La commutativité
    
      \begin{align*}
	2 + 3 &= 3 + 2\\
	4 + 5 &= 5 + 4\\
	a + b &= b + a
      \end{align*}          
    
    Dit simplement, l'ordre des termes n'a pas d'importance.
*** La différence
    
      \begin{align*}
	5 &= 3 + 2 \Rightarrow 3 = 5 - 2\\
	7 &= 3 + 4 \Rightarrow 3 = 7 - 4\\
	a &= b + c \Rightarrow b = a - c
      \end{align*}                             
    
*** L'associativité 
    
      \begin{align*}
	(1 + 2) + 3 = (3) + 3 = 6 &= 1 + (2 + 3) = 1 + (5)\\
	(4 + 5) + 6 = (9) + 6 = 15 &= 4 + (5 + 6) = 4 + (11)\\
	(a + b) + c &= a + (b + c)
      \end{align*}
    
*** Addition répétée
    
      \begin{align*}
	1 + 1 + 1 + 1 + 1 + 1 &= 1 \times 6\\
	2 + 2 + 2 &= 2\times 3\\
	3 + 3 + 3 + 3 &= 3\times 4
      \end{align*}
    
* La multiplication
  Dans $4 \times 2,5 = 10$ les facteurs sont 4 et 2,5 et 10 en est le
  produit.

  Tout nombre non nul admet un inverse : le produit de deux inverses est 1.
** Exemples 
   1. $\dfrac{1}{2} \times 2 = 1$
   2. $-\dfrac{2}{5} \times (-2,5) = 1$
   3. $\dfrac{3}{7} \times \dfrac{7}{3} = 1$
   4. $\dfrac{3}{\sqrt{2}} \times \dfrac{\sqrt{2}}{3} = 1$
   5. $\dfrac{1}{a} \times a = 1 (a \neq 0)$
** Exercice 2
   Trouver le nombre inverse dans chaque cas :
   1. L'inverse du nombre 3 est :
   2. L'inverse du nombre 0,5 est : 
   3. L'inverse de $-\dfrac{1}{3}$ est : 
   4. L'inverse de $\pi$ est :
   5. L'inverse de $-\dfrac{1}{a}$ est : 
** Propriétés
*** La commutativité
    \begin{align*}
      2 \times 3 &= 3\times 2\\
      \dfrac{2}{3} \times \dfrac{4}{5} &= \dfrac{4}{5}\times \dfrac{2}{3}\\
      a \times b &= b\times a
    \end{align*}
*** Le quotient
    \begin{align*}
      2\times 3 = 6 &\Rightarrow 3 = \dfrac{6}{2}\\
      5\times 7 = 35 &\Rightarrow 7 = \dfrac{35}{5}\\
      a\times b = c &\Rightarrow b = \dfrac{c}{a}
    \end{align*}
*** L'associativité
    \begin{align*}
      (2\times 3)\times 4 &= 2\times (3\times 4)\\
      (5\times 7)\times 9 &= 5\times (7\times 9)\\
      (a\times b)\times c &= a\times (b\times c)
    \end{align*}
*** Multiplication répétée
    \begin{align*}
      2\times 2\times 2 &= 2^3\\
      3\times 3\times 3\times 3 &= 3^4\\
      4\times 4\times 4\times 4\times 4 &= 4^5
    \end{align*}
* Les opérations avec les fractions
  Pour ajouter ou soustraire deux fractions il faut d'abord qu'elles
  aient le même dénominateur.
** Exemples
   + $\dfrac{2}{3} + \dfrac{5}{3} = \dfrac{8}{3}$
   + $\dfrac{7}{11} - \dfrac{5}{11} = \dfrac{2}{11}$
** Exercice 3
   Effectuer ces deux opérations : 

   + $\dfrac{5}{3} - \dfrac{2}{3} =$
   + $\dfrac{7}{11} + \dfrac{5}{11} =$
** Mise au même dénominateur
   Mettre au même dénominateur revient à déterminer le plus petit
   multiple commun entre les deux dénominateurs.
** Exemples
   1. $\dfrac{5}{6} + \dfrac{3}{4} = \dfrac{10}{12} + \dfrac{9}{12} = \dfrac{19}{12}$
   2. $\dfrac{15}{20} - \dfrac{7}{15} = \dfrac{45}{60} - \dfrac{28}{60} = \dfrac{17}{60}$
** Exercice 4
   Effectuer les opérations suivantes :
   1. $\dfrac{5}{6} - \dfrac{3}{4} =$
   2. $\dfrac{15}{20} + \dfrac{7}{15} =$ 
** Multiplication
   Pour les multiplications c'est très simple : on multiplie les
   numérateurs entre eux et les dénominateurs entre eux.
*** Exemples
    \begin{align*}
      \dfrac{2}{3}\times \dfrac{4}{5} &= \dfrac{8}{15}\\
      \dfrac{5}{6}\times \dfrac{1}{7} &= \dfrac{5}{42}\\
      \dfrac{10}{9}\times \dfrac{4}{7} &= \dfrac{40}{63}
    \end{align*}
*** Exercice 5
    Effectuer les opérations suivantes
    \begin{align*}
      \dfrac{9}{4}\times \dfrac{7}{5} &= \\
      \dfrac{6}{5}\times \dfrac{8}{5} &= \\
      \dfrac{9}{10}\times \dfrac{3}{7} &= 
    \end{align*}
** Division
   Pour diviser deux fractions, on multiplie la première par l'inverse
   de la seconde.
*** Exemples
    
      \begin{align*}
      \dfrac{2}{3} \div \dfrac{4}{5} &= \dfrac{10}{12}\\
      \dfrac{5}{6}\div \dfrac{1}{7} &= \dfrac{35}{6}\\
      \dfrac{10}{9}\div \dfrac{4}{7} &= \dfrac{70}{36}
      \end{align*}
    
*** Exercice 6
    Effectuer les opérations suivantes
    
      \begin{align*}
      \dfrac{9}{4}\div \dfrac{7}{5} &= \\
      \dfrac{6}{5}\div \dfrac{8}{5} &= \\
      \dfrac{9}{10}\div \dfrac{3}{7} &= 
      \end{align*}
    
* Solutions
** Exercice 1
   Trouver les nombres opposés aux nombres suivants :
   1. L'opposé du nombre $5$ est : $(-5)$ parce que $5 + (-5) = 5 - 5
      = 0$
   2. L'opposé du nombre $(-6)$ est : $6$ car $(-6) + 6 = 6 - 6 = 0$
   3. L'opposé du nombre $(-1,5)$ est : $1,5$ parce que $1,5 + (-1,5)
      = 1,5 - 1,5 = 0$
   4. L'opposé du nombre $\pi$ est : $-\pi$ car $\pi + (-\pi) = \pi -
      \pi = 0$
   5. L'opposé du nombre $-\dfrac{1}{3}$ est : $\dfrac{1}{3}$ parce
      que $-\dfrac{1}{3} + \dfrac{1}{3} = \dfrac{1}{3} - \dfrac{1}{3}
      = 0$
** Exercice 2
   Trouver le nombre inverse dans chaque cas :
   1. L'inverse du nombre 3 est : $\dfrac{1}{3}$ car $3\times
      \dfrac{1}{3} = 1$
   2. L'inverse du nombre 0,5 est : 2 car $0,5\times 2 = 1$
   3. L'inverse de $-\dfrac{1}{3}$ est : $-3$ car $-\dfrac{1}{3}\times
      (-3) = 1$
   4. L'inverse de $\pi$ est : $\dfrac{1}{\pi}$ car $\pi\times
      \dfrac{1}{\pi} = 1$
   5. L'inverse de $-\dfrac{1}{a}$ est : $-a$ car $-\dfrac{1}{a}\times
      (-a) = 1$
** Exercice 3
   Effectuer ces deux opérations : 

   + $\dfrac{5}{3} - \dfrac{2}{3} = \dfrac{5-2}{3} = \dfrac{3}{3} = 1$
   + $\dfrac{7}{11} + \dfrac{5}{11} = \dfrac{7+5}{11} =
     \dfrac{12}{11}$
** Exercice 4
   Effectuer les opérations suivantes :
   1. \begin{align*}
       A&=\dfrac{5}{6} - \dfrac{3}{4}\\
       A&=\dfrac{5\times 2}{6\times 2} - \dfrac{3\times 3}{4\times 3}\\
       A&=\dfrac{10 - 9}{12}\\
       A&=\dfrac{1}{12}
      \end{align*}

   2. \begin{align*}
       B&=\dfrac{15}{20} + \dfrac{7}{15}\\
       B&=\dfrac{15\times 3}{20\times 3} + \dfrac{7\times 4}{15\times 4}\\
       B&=\dfrac{45 + 28}{60}\\
       B&=\dfrac{73}{60}
      \end{align*}
