#+TITLE: Article 1
#+AUTHOR: Laurent Garnier

* Vocabulaire
Chaque semaine je te propose 35 mots. Pourquoi 35 mots ? Et bien parce
que ça fait 5 par jour. Et 5 par jour ça me semble plutôt
raisonnable. Si on considère que tu passes 2 minutes par mot alors ça
te fait 10 minutes par jour. 

Il se trouve que la régularité est le secret de tout succès. Alors il
vaut mieux consacrer 10 minutes chaque jour plutôt qu'une heure le
week-end. 

Concrètement, le matin au réveil tu relis tes 5 mots pendant 5
minutes. Une minute par mot le matin. Et la même chose le soir avant
de dormir. Facile, non ?

Et si ? Et bien si tu trouves que ça ne marche pas pour toi alors
essaie autre chose.
** Mot #1 : To strive
Ce mot a plusieurs sens. Il peut vouloir dire : faire tout son
possible. Comme dans l'injonction : Strive for success. Qui signifie :
Fais tout ton possible pour réussir.
Il a pour synonyme : to struggle. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/strive]]
+ [[https://en.oxforddictionaries.com/definition/strive]]
+ [[https://dictionary.cambridge.org/dictionary/english/strive]]
+ [[https://en.wiktionary.org/wiki/strive]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=strive]]

** Mot #2 : Remorse
Ce mot est issu du français /remords/ et il a le même sens.
Exemple : He has remorse because he cheats on his wife.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/remorse]]
+ [[https://en.oxforddictionaries.com/definition/remorse]]
+ [[https://dictionary.cambridge.org/dictionary/english/remorse]]
+ [[https://en.wiktionary.org/wiki/remorse]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=remorse]]
** Mot #3 : To wrack
Ce verbe signifie se venger. Exemple : If every general were wracked
with guilt after making after leading troops into deadly battles to
win wars, they would never do what was necessary to win. Si tous les
généraux étaient déchirés par la culpabilité après avoir conduit leurs
troupes dans des batailles meurtrières pour gagner des guerres, ils ne
feraient jamais ce qu'il fallait pour gagner.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/wrack]]
+ [[https://en.oxforddictionaries.com/definition/wrack]]
+ [[https://dictionary.cambridge.org/dictionary/english/wrack]]
+ [[https://en.wiktionary.org/wiki/wrack]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=wrack]]

** Mot #4 : Prone
Cet adjectif signifie avoir tendance à. Par exemple : Some studies
have found that power lowers empathy and that powerful people are
prone to treating others as subhuman. Certaines études ont montré que
le pouvoir diminue l'empathie et que les gens puissants sont enclins à
traiter les autres comme des sous-humains. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/prone]]
+ [[https://en.oxforddictionaries.com/definition/prone]]
+ [[https://dictionary.cambridge.org/dictionary/english/prone]]
+ [[https://en.wiktionary.org/wiki/prone]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=prone]]

** Mot #5 : Thereby
Ce mot signifie ainsi. Comme par exemple dans la phrase : According to
other studies, confidence increases productivity and causes people to
take on more challenging tasks, thereby making them stand out as
shining stars in the workplace. Selon d'autres études, la confiance
augmente la productivité et pousse les gens à assumer des tâches plus
difficiles, ce qui les fait ressortir comme des vedettes brillantes sur
leur lieu de travail.
*** Pour aller plus loin 
+ [[http://www.wordreference.com/enfr/thereby]]
+ [[https://en.oxforddictionaries.com/definition/thereby]]
+ [[https://dictionary.cambridge.org/dictionary/english/thereby]]
+ [[https://en.wiktionary.org/wiki/thereby]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=thereby]]
** Mot #6 : Overly
Ce mot signifie trop. Par exemple dans la phrase : Research has even
shown that overly confident people have better chances of receiving a
promotion than their less confident colleagues, even if the latter are
more accomplished. La recherche a même montré que les personnes trop
confiantes ont de meilleures chances de recevoir une promotion que
leurs collègues moins confiants, même si ces derniers sont plus
accompli.
*** Pour aller plus loin
+ http://www.wordreference.com/enfr/overly
+ https://en.oxforddictionaries.com/definition/overly
+ [[https://dictionary.cambridge.org/dictionary/english/overly]]
+ [[https://en.wiktionary.org/wiki/overly]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=overly]]
** Mot #7 : To hone
Ce verbe a plusieurs sens : aiguiser, affûter, parfaire. Comme par
exemple dans la phrase : Meanwhile, introverts don't worry about other
people bothering them, and have plenty of time to hone their
skills. Pendant ce temps, les introvertis ne s'inquiètent pas que
d'autres personnes les dérangent, et ont beaucoup de temps pour
perfectionner leurs compétences.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/hone]]
+ [[https://en.oxforddictionaries.com/definition/hone]]
+ [[https://dictionary.cambridge.org/dictionary/english/hone]]
+ [[https://en.wiktionary.org/wiki/hone]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=hone]]

** Mot #8 : Grueling
Cet adjectif signifie éteintant, épuisant, exténuant. Par exemple : To
ensure that a greater percentage of candidates made it through the
grueling initiation ritual known as "Hell Week", they began teaching
candidates to use positive self-talk. Pour s'assurer qu'un plus grand
pourcentage de candidats réussisse le rituel d'initiation exténuant
connu sous le nom de «semaine de l'enfer», ils ont commencé à
enseigner aux candidats à utiliser le monologue intérieur positif.
*** Pour aller plus loin 
+ [[http://www.wordreference.com/enfr/grueling]]
+ [[https://en.oxforddictionaries.com/definition/gruelling]]
+ [[https://dictionary.cambridge.org/dictionary/english/grueling]]
+ [[https://en.wiktionary.org/wiki/grueling]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=grueling]]
** Mot #9 : Grit
Ce mot peut être un nom et dans ce cas il peut désigner la poussière
ou le courage, l'endurance. Par exemple dans la phrase : In other
words, optimism keeps people going, but true grit is more than
positive thinking. En d'autres termes, l'optimisme maintient les gens
en marche, mais le vrai courage est plus que la pensée positive.
Mais il peut aussi être un verbe (peu usité) qui signifie couvrir de
poussière ou serrer les dents. Par exemple : We had no choice but to
grit our teeth and get on with it. Nous n'avions pas d'autre choix que
de serrer les dents et de continuer.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/grit]]
+ [[https://en.oxforddictionaries.com/definition/grit]]
+ [[https://dictionary.cambridge.org/dictionary/english/grit]]
+ [[https://en.wiktionary.org/wiki/grit#Verb]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=grit]]
** Mot #10 : Weary
Ce mot appartient au registre soutenu, il signifie las, fatigué,
épuisé. Par exemple dans la phrase : I'm starting to weary of
advertising on the web. Je commence à être las de la publicité sur le
web. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/weary]]
+ [[https://en.oxforddictionaries.com/definition/weary]]
+ [[https://dictionary.cambridge.org/dictionary/english/weary]]
+ [[https://en.wiktionary.org/wiki/weary]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=weary]]
** Mot #11 : Keyed
Cet adjectif signifie accordé, saisi. Par exemple dans la phrase :
Brief ads are never keyed. Les petites publicités ne sont jamais saisies.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/keyed]]
+ [[https://en.oxforddictionaries.com/definition/keyed]]
+ [[https://dictionary.cambridge.org/dictionary/english/key?q=keyed]]
+ [[https://en.wiktionary.org/wiki/keyed]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=keyed]]
** Mot #12 : Gracless
Cet adjectif signifie dépourvu de grâce. Comme par exemple dans la
phrase : Don’t be put off by Hopkins’ saccadé, graceless style. Ne
soyez pas rebutés par le style staccato et disgracieux de Hopkins.

*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/graceless]]
+ [[https://en.oxforddictionaries.com/definition/graceless]]
+ [[https://dictionary.cambridge.org/dictionary/english/graceless]]
+ [[https://en.wiktionary.org/wiki/graceless]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=graceless]]
*** Remarque utile
Graceless fait partie des mots qui se construisent de manière
*logique*. En effet, si vous repérez le radical /grace/ qui est comme
son analogue français et que vous comprenez le sens du suffixe /less/
alors vous pouvez comprendre le sens de nombreux mots comme par
exemples :

| English       | Français         |
|---------------+------------------|
| use*less*     | *in*utile        |
| meaning*less* | *in*sensé        |
| regard*less*  | *in*dépendamment |
| fruit*less*   | *in*fructueux    |
** Mot #13 : Staccato
Ce mot d'origine italienne appartient au champ lexical de la musique
et peut être utilisé en tant qu'adjectif, adverbe ou nom. Par
extension il a pris le sens de saccadé. Par exemple : I added quarter
tone grace notes to Debussy's original staccato descending
gesture. J'ai ajouté des appogiatures brèves (acciacatura) au geste
descendant staccato de Debussy. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/staccato]]
+ [[https://en.oxforddictionaries.com/definition/staccato]]
+ [[https://dictionary.cambridge.org/dictionary/english/staccato]]
+ [[https://en.wiktionary.org/wiki/staccato]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=staccato]]
** Mot #14 : Impetus
Ce nom signifie impulsion, élan. Comme par exemple dans la phrase :
The funding gave fresh impetus to the project. Le financement a donné
un nouveau souffle au projet. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/impetus]]
+ [[https://en.oxforddictionaries.com/definition/impetus]]
+ [[https://dictionary.cambridge.org/dictionary/english/impetus]]
+ [[https://en.wiktionary.org/wiki/impetus]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=impetus]]
** Mot #15 : To glean
Ce verbe issu du vieux français signifie glaner. Comme dans la
phrase : Otherwise, you won’t be able to glean the gems it contains
and that would be a waste. Sinon, vous ne serez pas en mesure de
glaner les gemmes qu'il contient et ce serait du gaspillage.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/gem]]
+ [[https://en.oxforddictionaries.com/definition/glean]]
+ [[https://dictionary.cambridge.org/dictionary/english/glean]]
+ [[https://en.wiktionary.org/wiki/glean]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=glean]]
** Mot #16 : Frantic
Cet adjectif est dérivé du mot français frénétique et a le même
sens. Comme dans la phrase : It's a frantic race to the shops when
sales begin. C'est une course effrénée vers les magasins lorsque les
soldes commencent.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/frantic]]
+ [[https://en.oxforddictionaries.com/definition/frantic]]
+ [[https://dictionary.cambridge.org/dictionary/english/frantic]]
+ [[https://en.wiktionary.org/wiki/frantic]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=frantic]]
** Mot #17 : Mellow
Ce mot peut être adjectif ou verbe. Dans les deux cas il porte le même
sens de doux, moelleux, velouté, adoucir. Comme par exemple dans la
phrase : Mellow mood has got me, so let the music rock me. L'humeur
douce m'a pris, alors laissez la musique me bercer. (Extrait de la
chanson [[https://youtu.be/i66Rq4oFjnU][Mellow Mood]] de Bob Marley).
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/mellow]]
+ [[https://en.oxforddictionaries.com/definition/mellow]]
+ [[https://dictionary.cambridge.org/dictionary/english/mellow]]
+
  [[https://en.wiktionary.org/wiki/mellow]]https://en.wiktionary.org/wiki/mellow
+ [[https://www.linguee.com/english-french/search?source=auto&query=mellow]]
