#+TITLE: Article 1
#+AUTHOR: Laurent Garnier

* Vocabulaire
Chaque semaine je te propose 35 mots. Pourquoi 35 mots ? Et bien parce
que ça fait 5 par jour. Et 5 par jour ça me semble plutôt
raisonnable. Si on considère que tu passes 2 minutes par mot alors ça
te fait 10 minutes par jour. 

Il se trouve que la régularité est le secret de tout succès. Alors il
vaut mieux consacrer 10 minutes chaque jour plutôt qu'une heure le
week-end. 

Concrètement, le matin au réveil tu relis tes 5 mots pendant 5
minutes. Une minute par mot le matin. Et la même chose le soir avant
de dormir. Facile, non ?

Et si ? Et bien si tu trouves que ça ne marche pas pour toi alors
essaie autre chose.
** Mot #1 : To strive
Ce mot a plusieurs sens. Il peut vouloir dire : faire tout son
possible. Comme dans l'injonction : Strive for success. Qui signifie :
Fais tout ton possible pour réussir.
Il a pour synonyme : to struggle. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/strive]]
+ [[https://en.oxforddictionaries.com/definition/strive]]
+ [[https://dictionary.cambridge.org/dictionary/english/strive]]
+ [[https://en.wiktionary.org/wiki/strive]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=strive]]

** Mot #2 : Remorse
Ce mot est issu du français /remords/ et il a le même sens.
Exemple : He has remorse because he cheats on his wife.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/remorse]]
+ [[https://en.oxforddictionaries.com/definition/remorse]]
+ [[https://dictionary.cambridge.org/dictionary/english/remorse]]
+ [[https://en.wiktionary.org/wiki/remorse]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=remorse]]
** Mot #3 : To wrack
Ce verbe signifie se venger. Exemple : If every general were wracked
with guilt after making after leading troops into deadly battles to
win wars, they would never do what was necessary to win. Si tous les
généraux étaient déchirés par la culpabilité après avoir conduit leurs
troupes dans des batailles meurtrières pour gagner des guerres, ils ne
feraient jamais ce qu'il fallait pour gagner.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/wrack]]
+ [[https://en.oxforddictionaries.com/definition/wrack]]
+ [[https://dictionary.cambridge.org/dictionary/english/wrack]]
+ [[https://en.wiktionary.org/wiki/wrack]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=wrack]]

** Mot #4 : Prone
Cet adjectif signifie avoir tendance à. Par exemple : Some studies
have found that power lowers empathy and that powerful people are
prone to treating others as subhuman. Certaines études ont montré que
le pouvoir diminue l'empathie et que les gens puissants sont enclins à
traiter les autres comme des sous-humains. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/prone]]
+ [[https://en.oxforddictionaries.com/definition/prone]]
+ [[https://dictionary.cambridge.org/dictionary/english/prone]]
+ [[https://en.wiktionary.org/wiki/prone]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=prone]]

** Mot #5 : Thereby
Ce mot signifie ainsi. Comme par exemple dans la phrase : According to
other studies, confidence increases productivity and causes people to
take on more challenging tasks, thereby making them stand out as
shining stars in the workplace. Selon d'autres études, la confiance
augmente la productivité et pousse les gens à assumer des tâches plus
difficiles, ce qui les fait ressortir comme des vedettes brillantes sur
leur lieu de travail.
*** Pour aller plus loin 
+ [[http://www.wordreference.com/enfr/thereby]]
+ [[https://en.oxforddictionaries.com/definition/thereby]]
+ [[https://dictionary.cambridge.org/dictionary/english/thereby]]
+ [[https://en.wiktionary.org/wiki/thereby]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=thereby]]
** Mot #6 : Overly
Ce mot signifie trop. Par exemple dans la phrase : Research has even
shown that overly confident people have better chances of receiving a
promotion than their less confident colleagues, even if the latter are
more accomplished. La recherche a même montré que les personnes trop
confiantes ont de meilleures chances de recevoir une promotion que
leurs collègues moins confiants, même si ces derniers sont plus
accompli.
*** Pour aller plus loin
+ http://www.wordreference.com/enfr/overly
+ https://en.oxforddictionaries.com/definition/overly
+ [[https://dictionary.cambridge.org/dictionary/english/overly]]
+ [[https://en.wiktionary.org/wiki/overly]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=overly]]
** Mot #7 : To hone
Ce verbe a plusieurs sens : aiguiser, affûter, parfaire. Comme par
exemple dans la phrase : Meanwhile, introverts don't worry about other
people bothering them, and have plenty of time to hone their
skills. Pendant ce temps, les introvertis ne s'inquiètent pas que
d'autres personnes les dérangent, et ont beaucoup de temps pour
perfectionner leurs compétences.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/hone]]
+ [[https://en.oxforddictionaries.com/definition/hone]]
+ [[https://dictionary.cambridge.org/dictionary/english/hone]]
+ [[https://en.wiktionary.org/wiki/hone]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=hone]]

** Mot #8 : Grueling
Cet adjectif signifie éteintant, épuisant, exténuant. Par exemple : To
ensure that a greater percentage of candidates made it through the
grueling initiation ritual known as "Hell Week", they began teaching
candidates to use positive self-talk. Pour s'assurer qu'un plus grand
pourcentage de candidats réussisse le rituel d'initiation exténuant
connu sous le nom de «semaine de l'enfer», ils ont commencé à
enseigner aux candidats à utiliser le monologue intérieur positif.
*** Pour aller plus loin 
+ [[http://www.wordreference.com/enfr/grueling]]
+ [[https://en.oxforddictionaries.com/definition/gruelling]]
+ [[https://dictionary.cambridge.org/dictionary/english/grueling]]
+ [[https://en.wiktionary.org/wiki/grueling]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=grueling]]
** Mot #9 : Grit
Ce mot peut être un nom et dans ce cas il peut désigner la poussière
ou le courage, l'endurance. Par exemple dans la phrase : In other
words, optimism keeps people going, but true grit is more than
positive thinking. En d'autres termes, l'optimisme maintient les gens
en marche, mais le vrai courage est plus que la pensée positive.
Mais il peut aussi être un verbe (peu usité) qui signifie couvrir de
poussière ou serrer les dents. Par exemple : We had no choice but to
grit our teeth and get on with it. Nous n'avions pas d'autre choix que
de serrer les dents et de continuer.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/grit]]
+ [[https://en.oxforddictionaries.com/definition/grit]]
+ [[https://dictionary.cambridge.org/dictionary/english/grit]]
+ [[https://en.wiktionary.org/wiki/grit#Verb]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=grit]]
** Mot #10 : Weary
Ce mot appartient au registre soutenu, il signifie las, fatigué,
épuisé. Par exemple dans la phrase : I'm starting to weary of
advertising on the web. Je commence à être las de la publicité sur le
web. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/weary]]
+ [[https://en.oxforddictionaries.com/definition/weary]]
+ [[https://dictionary.cambridge.org/dictionary/english/weary]]
+ [[https://en.wiktionary.org/wiki/weary]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=weary]]
** Mot #11 : Keyed
Cet adjectif signifie accordé, saisi. Par exemple dans la phrase :
Brief ads are never keyed. Les petites publicités ne sont jamais saisies.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/keyed]]
+ [[https://en.oxforddictionaries.com/definition/keyed]]
+ [[https://dictionary.cambridge.org/dictionary/english/key?q=keyed]]
+ [[https://en.wiktionary.org/wiki/keyed]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=keyed]]
** Mot #12 : Gracless
Cet adjectif signifie dépourvu de grâce. Comme par exemple dans la
phrase : Don’t be put off by Hopkins’ saccadé, graceless style. Ne
soyez pas rebutés par le style staccato et disgracieux de Hopkins.

*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/graceless]]
+ [[https://en.oxforddictionaries.com/definition/graceless]]
+ [[https://dictionary.cambridge.org/dictionary/english/graceless]]
+ [[https://en.wiktionary.org/wiki/graceless]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=graceless]]
*** Remarque utile
Graceless fait partie des mots qui se construisent de manière
*logique*. En effet, si vous repérez le radical /grace/ qui est comme
son analogue français et que vous comprenez le sens du suffixe /less/
alors vous pouvez comprendre le sens de nombreux mots comme par
exemples :

| English       | Français         |
|---------------+------------------|
| use*less*     | *in*utile        |
| meaning*less* | *in*sensé        |
| regard*less*  | *in*dépendamment |
| fruit*less*   | *in*fructueux    |
** Mot #13 : Staccato
Ce mot d'origine italienne appartient au champ lexical de la musique
et peut être utilisé en tant qu'adjectif, adverbe ou nom. Par
extension il a pris le sens de saccadé. Par exemple : I added quarter
tone grace notes to Debussy's original staccato descending
gesture. J'ai ajouté des appogiatures brèves (acciacatura) au geste
descendant staccato de Debussy. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/staccato]]
+ [[https://en.oxforddictionaries.com/definition/staccato]]
+ [[https://dictionary.cambridge.org/dictionary/english/staccato]]
+ [[https://en.wiktionary.org/wiki/staccato]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=staccato]]
** Mot #14 : Impetus
Ce nom signifie impulsion, élan. Comme par exemple dans la phrase :
The funding gave fresh impetus to the project. Le financement a donné
un nouveau souffle au projet. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/impetus]]
+ [[https://en.oxforddictionaries.com/definition/impetus]]
+ [[https://dictionary.cambridge.org/dictionary/english/impetus]]
+ [[https://en.wiktionary.org/wiki/impetus]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=impetus]]
** Mot #15 : To glean
Ce verbe issu du vieux français signifie glaner. Comme dans la
phrase : Otherwise, you won’t be able to glean the gems it contains
and that would be a waste. Sinon, vous ne serez pas en mesure de
glaner les gemmes qu'il contient et ce serait du gaspillage.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/gem]]
+ [[https://en.oxforddictionaries.com/definition/glean]]
+ [[https://dictionary.cambridge.org/dictionary/english/glean]]
+ [[https://en.wiktionary.org/wiki/glean]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=glean]]
** Mot #16 : Frantic
Cet adjectif est dérivé du mot français frénétique et a le même
sens. Comme dans la phrase : It's a frantic race to the shops when
sales begin. C'est une course effrénée vers les magasins lorsque les
soldes commencent.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/frantic]]
+ [[https://en.oxforddictionaries.com/definition/frantic]]
+ [[https://dictionary.cambridge.org/dictionary/english/frantic]]
+ [[https://en.wiktionary.org/wiki/frantic]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=frantic]]
** Mot #17 : Mellow
Ce mot peut être adjectif ou verbe. Dans les deux cas il porte le même
sens de doux, moelleux, velouté, adoucir. Comme par exemple dans la
phrase : Mellow mood has got me, so let the music rock me. L'humeur
douce m'a pris, alors laissez la musique me bercer. (Extrait de la
chanson [[https://youtu.be/i66Rq4oFjnU][Mellow Mood]] de Bob Marley).
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/mellow]]
+ [[https://en.oxforddictionaries.com/definition/mellow]]
+ [[https://dictionary.cambridge.org/dictionary/english/mellow]]
+ [[https://en.wiktionary.org/wiki/mellow]]https://en.wiktionary.org/wiki/mellow
+ [[https://www.linguee.com/english-french/search?source=auto&query=mellow]]
** Mot #18 : Ominous
Cet adjectif est issu du latin ominosus et signifie menaçant. Comme
dans la phrase : The dark clouds on the horizon were ominous. Les
nuages noirs à l'horizon étaient de mauvais augure.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/ominous]]
+ [[https://en.oxforddictionaries.com/definition/ominous]]
+ [[https://dictionary.cambridge.org/dictionary/english/ominous]]
+ [[https://en.wiktionary.org/wiki/ominous]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=ominous]]
** Mot #19 : To broaden
Ce verbe signifie élargir. Comme par exemple : The company launched a
marketing campaign to broaden its customer base. L'entreprise a lancé
une campagne de communication pour élargir sa clientèle.
*** Pour aller plus loin 
+ [[http://www.wordreference.com/enfr/broaden]]
+ [[https://en.oxforddictionaries.com/definition/broaden]]
+ [[https://dictionary.cambridge.org/dictionary/english/broaden]]
+ [[https://en.wiktionary.org/wiki/broaden]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=broaden]]
** Mot #20 : To muster
Ce verbe peut aussi être décliné en nom et il signifie dans les deux
cas l'idée de rassembler, de rassemblement. Comme par exemple dans la
phrase : It is our duty to muster our defences against these
destabilising forces. Il est de notre devoir de rassembler nos forces contre ces puissances déstabilisatrices.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/muster]]
+ [[https://en.oxforddictionaries.com/definition/muster]]
+ [[https://dictionary.cambridge.org/dictionary/english/muster]]
+ [[https://en.wiktionary.org/wiki/muster]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=muster]]
** Mot #21 : Chore
Ce mot signifie corvée. Comme dans la phrase : Ironing is not a chore
for her. Repasser n'est pas une corvée pour elle.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/chore]]
+ [[https://en.oxforddictionaries.com/definition/chore]]
+ [[https://dictionary.cambridge.org/dictionary/english/chore]]
+ [[https://en.wiktionary.org/wiki/chore]]
+
  [[https://www.linguee.com/english-french/search?source=auto&query=chore]]
** Mot #22 : Slender
Cet adjectif signifie mince, élancé. Comme dans la phrase : She has
long and slender legs. Elle a des jambes longues et minces.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/slender]]
+ [[https://en.oxforddictionaries.com/definition/slender]]
+ [[https://dictionary.cambridge.org/dictionary/english/slender]]
+ [[https://en.wiktionary.org/wiki/slender]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=slender]]
** Mot #23 : To mend
Ce verbe peut aussi être décliné en nom et signifie raccommoder,
réparer, une reprise. Par exemple : I did not want to mend my old
socks, so I just bought new ones. Je ne voulais pas repriser mes
vieilles chaussettes, donc j'en ai racheté.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/mend]]
+ [[https://en.oxforddictionaries.com/definition/mend]]
+ [[https://dictionary.cambridge.org/dictionary/english/mend]]
+ [[https://en.wiktionary.org/wiki/mend]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=mend]]
** Mot #24 : Craftsman
Ce mot signifie artisan. Comme dans l'exemple : He is a careful
craftsman. C'est un artisan minutieux. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/craftsman]]
+ [[https://en.oxforddictionaries.com/definition/craftsman]]
+ [[https://dictionary.cambridge.org/dictionary/english/craftsman]]
+ [[https://en.wiktionary.org/wiki/craftsman]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=craftsman]]
*** Remarque utile
De nombreux mots anglais suivent ce même schéma consistant à ajouter
le suffixe /man/ ou /woman/ pour créer un nouveau mot à partir d'un
radical déjà existant. En voici quelques exemples :
| English       | Français             |
|---------------+----------------------|
| police*man*   | policier             |
| police*woman* | policière            |
| fire*man*     | pompier              |
| post*man*     | facteur (ou postier) |

Dans notre cas /crafts*man*/ vient de /craft/ qui veut dire métier
manuel, art, habileté.
** Mot #25 : Coffin
Ce mot est issu du vieu français /cofin/ et signifie cercueil, il
existe également sous la forme de verbe (mettre dans un cercueil). Par
exemple : This caricature shows the grim reaper with his scythe aboard
a chariot bearing a coffin. Cette caricature représente la mort munie
de sa faux, déambulant à bord d'une charrette chargée d'un cercueil. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/coffin]]
+ [[http://www.wordreference.com/enfr/coffin]]
+ [[https://dictionary.cambridge.org/dictionary/english/coffin]]
+ [[https://en.wiktionary.org/wiki/coffin]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=coffin]]
** Mot #26 : Vessel
Issu de l'anglo-normand vessel depuis le latin tardif vascellum, ce
mot signifie vaisseau. Comme par exemple dans : The vessel sailed
around the globe. Le vaisseau a navigué autour du monde.
*** Pour aller plus loin
+ http://www.wordreference.com/enfr/vessel
+ [[https://en.oxforddictionaries.com/definition/vessel]]
+ [[https://dictionary.cambridge.org/dictionary/english/vessel]]
+ [[https://en.wiktionary.org/wiki/vessel]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=vessel]]
** Mot #27 : Casket
Ce mot est issu de l'anglo-normand /cassette/ et il signifie coffret
(et parfois cercueil). Par exemple : It is kept in a casket encrusted
with precious stones. Elle est conservée dans coffret recouvert de
pierres précieuses. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/casket]]
+ [[https://en.oxforddictionaries.com/definition/casket]]
+ [[https://dictionary.cambridge.org/dictionary/english/casket]]
+ [[https://en.wiktionary.org/wiki/casket]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=casket]]
** Mot #28 : Gleaming
Cet adjectif signifie brillant, étincelant. Par exemple : Selected raw
materials and careful manufacture provide high-quality and gleaming
crystal. Des matières premières choisies et une manufacture sensible
garantissent un verre de cristal de haute qualité et brillant. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/gleaming]]
+ [[https://en.oxforddictionaries.com/definition/gleaming]]
+ [[https://dictionary.cambridge.org/dictionary/english/gleaming]]
+ [[https://en.wiktionary.org/wiki/gleaming]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=gleaming]]
** Mot #29 : Burial
Ce mot est d'origine germanique et signifie enterrement,
obsèque... bref, il appartient au champ lexical funéraire. En voici un
exemple : The burial will take place in the village cemetery. L'inhumation aura lieu au cimetière du village.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/burial]]
+ [[https://en.oxforddictionaries.com/definition/burial]]
+ [[https://dictionary.cambridge.org/dictionary/english/burial]]
+ [[https://en.wiktionary.org/wiki/burial]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=burial]]
** Mot #30 : Hoard
Ce mot d'origine germanique se décline également en verbe et signifie
réserve ou faire des réserves. Par exemple : It will be particularly
favourable for all forms of investments and savings (we all know that
rodents hoard their food)".  « Elle sera particulièrement favorable à
l'épargne (on connaît la tendance du rongeur à l'accumulation de réserves de nourritures) et aux investissements sous toutes les formes ».

*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/hoard]]
+ [[https://en.oxforddictionaries.com/definition/hoard]]
+ [[https://dictionary.cambridge.org/dictionary/english/hoard]]
+ [[https://en.wiktionary.org/wiki/hoard]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=hoard]]
** Mot #31 : Sketch
Ce mot serait d'origine hollandaise ou allemande via l'italien depuis
le grec... Bref il a voyagé. Il peut également être sous la forme de
verbe et signifie croquis, esquisser. Par exemple : The painter made
the sketch of her future painting. La peintre a dessiné l'ébauche de son futur tableau.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/sketch]]
+ [[https://en.oxforddictionaries.com/definition/sketch]]
+ [[https://dictionary.cambridge.org/dictionary/english/sketch]]
+ [[https://en.wiktionary.org/wiki/sketch]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=sketch]]
** Mot #32 : Nasty
Il peut être adjectif ou nom et signifie méchant, mauvais,
vilain. Comme par exemple : [[https://youtu.be/pqL6YCLI1CU][Hello]] nasty. Bonjour méchant. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/nasty]]
+ [[https://en.oxforddictionaries.com/definition/nasty]]
+ [[https://dictionary.cambridge.org/dictionary/english/nasty]]
+ [[https://en.wiktionary.org/wiki/nasty]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=nasty]]
** Mot #33 : Bout
Mot d'origine germanique signifiant accès, poussée, quinte. Comme dans
l'exemple : A severe bout of flu. Une grave grippe. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/bout]]
+ [[https://en.oxforddictionaries.com/definition/bout]]
+ [[https://dictionary.cambridge.org/dictionary/english/bout]]
+ [[https://en.wiktionary.org/wiki/bout#English]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=bout]]
** Mot #34 : Jaundice
Ce mot est issu du vieux français et signifie jaunisse. Comme par
exemple : Jaundice is a serious medical condition. La jaunisse est une
maladie sérieuse.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/jaundice]]
+ [[https://en.oxforddictionaries.com/definition/jaundice]]
+ [[https://dictionary.cambridge.org/dictionary/english/jaundice]]
+ [[https://en.wiktionary.org/wiki/jaundice][https://en.wiktionary.org/wiki/jaundice]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=jaundice]]
** Mot #35 : Sallow
Ce mot d'origine germanique et relié au vieu norrois signifie cireux,
rendre jaunâtre. Comme dans l'exemple : He was undersized with a
sallow complexion, a mat of black hair, and prominent teeth. Il était sous-dimensionné avec un teint hâlé, une natte de cheveux noirs et des dents proéminentes.

*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/sallow]]
+ [[https://en.oxforddictionaries.com/definition/sallow]]
+ [[https://dictionary.cambridge.org/dictionary/english/sallow]]
+ [[https://en.wiktionary.org/wiki/sallow]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=sallow]]
** Bonus #1 : Willow
Ce mot d'origine germanique signifie saule (l'arbre ou le bois). Comme
par exemple : [[https://youtu.be/gUHa0Rm0cXw][Willow]]s are beautiful trees. Les saules sont des arbres
magnifiques. 
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/willow]]
+ [[https://en.oxforddictionaries.com/definition/willow]]
+ [[https://dictionary.cambridge.org/dictionary/english/willow]]
+ [[https://en.wiktionary.org/wiki/willow]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=willow]]
** Bonus #2 : Breeches
Ce mot ancien signifie hauts-de-chausses, culotte, pantalaon. Par
exemple : As for knee breeches, they date only from the late 18th
century. Quant aux culottes de genou, elles ne datent que de la fin du XVIIIe siècle.
*** Pour aller plus loin
+ [[http://www.wordreference.com/enfr/breeches]]
+ [[https://en.oxforddictionaries.com/definition/breeches]]
+ [[https://dictionary.cambridge.org/dictionary/english/breeches]]
+ [[https://en.wiktionary.org/wiki/breeches]]
+ [[https://www.linguee.com/english-french/search?source=auto&query=breeches]]
